baseURL = "https://umarahmad.xyz/"
languageCode = "en-us"
title = "Umar Ahmad"
theme="bearblog"
publishDir="../blog-gen/"
ignoreFiles = [ "^\\..*$", ".*umar@umarbook\\.local.*$", "flycheck_.*$"]

# [taxonomies]
#     tag = "tags"
